/**
 * Stable, machine-readable error codes for the response envelope (see
 * `lib/response.ts`). English constants, Spanish `message` text — matches
 * the rest of the project's language split (identifiers in English/code
 * conventions, user- and dev-facing text in Spanish).
 */
export const ErrorCode = {
	NOT_FOUND: 'NOT_FOUND',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	// Request-body failures raised by express.json() (body-parser) before any
	// route runs — see middleware/error-handler.ts.
	INVALID_JSON: 'INVALID_JSON',
	PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
	UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
	BAD_REQUEST: 'BAD_REQUEST',
	// A %-escape in a URL segment that can't be decoded (/public/partidos/%zz).
	INVALID_URL_ENCODING: 'INVALID_URL_ENCODING',
	RATE_LIMITED: 'RATE_LIMITED',
	// Auth (T-03).
	UNAUTHENTICATED: 'UNAUTHENTICATED',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	FORBIDDEN: 'FORBIDDEN',
	USER_NOT_VALIDATED: 'USER_NOT_VALIDATED',
	CSRF_FAILED: 'CSRF_FAILED',
	EMAIL_TAKEN: 'EMAIL_TAKEN',
	// Participants (T-04).
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	PAYMENT_ALREADY_CONFIRMED: 'PAYMENT_ALREADY_CONFIRMED',
	PAYMENT_NOT_CONFIRMED: 'PAYMENT_NOT_CONFIRMED',
	USER_ALREADY_VALIDATED: 'USER_ALREADY_VALIDATED',
	NOT_A_PARTICIPANT: 'NOT_A_PARTICIPANT',
	ADMIN_CANNOT_BET: 'ADMIN_CANNOT_BET',
	// Coins (T-05).
	INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
	MOVEMENT_ALREADY_APPLIED: 'MOVEMENT_ALREADY_APPLIED',
	SELECTION_NOT_DEBITED: 'SELECTION_NOT_DEBITED',
	// Sports catalog (T-06).
	SPORT_NOT_FOUND: 'SPORT_NOT_FOUND',
	COMPETITION_NOT_FOUND: 'COMPETITION_NOT_FOUND',
	TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
	PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
	ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
	SLUG_TAKEN: 'SLUG_TAKEN',
	PLAYER_ALREADY_ENROLLED: 'PLAYER_ALREADY_ENROLLED',
	SHIRT_NUMBER_TAKEN: 'SHIRT_NUMBER_TAKEN',
	COMPETITION_MISMATCH: 'COMPETITION_MISMATCH',
	TRANSFER_NOT_ALLOWED: 'TRANSFER_NOT_ALLOWED',
	SPORT_IN_USE: 'SPORT_IN_USE',
	COMPETITION_IN_USE: 'COMPETITION_IN_USE',
	TEAM_IN_USE: 'TEAM_IN_USE',
	PLAYER_IN_USE: 'PLAYER_IN_USE',
	ENROLLMENT_IN_USE: 'ENROLLMENT_IN_USE',
	DRAW_RULE_LOCKED: 'DRAW_RULE_LOCKED',
	// Matches (T-07).
	MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
	SAME_TEAM: 'SAME_TEAM',
	MATCH_DATE_IN_PAST: 'MATCH_DATE_IN_PAST',
	MATCH_LOCKED: 'MATCH_LOCKED',
	MATCH_NOT_PROGRAMMED: 'MATCH_NOT_PROGRAMMED',
	MATCH_HAS_BETS: 'MATCH_HAS_BETS',
	MATCH_HAS_GOALS: 'MATCH_HAS_GOALS',
	INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
	// Results (T-12).
	RESULT_NOT_ALLOWED_YET: 'RESULT_NOT_ALLOWED_YET',
	RESULT_INCOMPLETE: 'RESULT_INCOMPLETE',
	MATCH_NOT_ENDED: 'MATCH_NOT_ENDED',
	RESULT_ALREADY_CONFIRMED: 'RESULT_ALREADY_CONFIRMED',
	RESULT_CHANGED: 'RESULT_CHANGED',
	MATCH_HAS_RESULT: 'MATCH_HAS_RESULT',
	// Goals and media (T-13).
	MATCH_NOT_STARTED: 'MATCH_NOT_STARTED',
	MATCH_HAS_MEDIA: 'MATCH_HAS_MEDIA',
	GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
	TEAM_NOT_IN_MATCH: 'TEAM_NOT_IN_MATCH',
	PLAYER_NOT_IN_TEAM: 'PLAYER_NOT_IN_TEAM',
	GOALS_EXCEED_SCORE: 'GOALS_EXCEED_SCORE',
	SCORE_BELOW_GOALS: 'SCORE_BELOW_GOALS',
	MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
	MEDIA_LIMIT_REACHED: 'MEDIA_LIMIT_REACHED',
	VIDEO_ALREADY_ADDED: 'VIDEO_ALREADY_ADDED',
	// Cancellation (T-16).
	MATCH_ALREADY_FINISHED: 'MATCH_ALREADY_FINISHED',
	MATCH_ALREADY_CANCELLED: 'MATCH_ALREADY_CANCELLED',
	IMAGE_INVALID: 'IMAGE_INVALID',
	UPLOAD_INVALID: 'UPLOAD_INVALID',
	FILE_NOT_FOUND: 'FILE_NOT_FOUND',
	// A warning, not an error: the result preview reports goals without a scorer (T-13).
	GOALS_UNATTRIBUTED: 'GOALS_UNATTRIBUTED',
	// Selections (T-09), reported per selection in the ticket preview.
	BETTING_CLOSED: 'BETTING_CLOSED',
	DRAW_NOT_ALLOWED: 'DRAW_NOT_ALLOWED',
	// Tickets (T-10).
	TICKET_REJECTED: 'TICKET_REJECTED',
	TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
	IDEMPOTENCY_KEY_INVALID: 'IDEMPOTENCY_KEY_INVALID',
	IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
	// Database constraint violations with no specific mapping (lib/db-errors.ts).
	DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
	RESOURCE_IN_USE: 'RESOURCE_IN_USE',
	INVALID_REFERENCE: 'INVALID_REFERENCE',
	// A deadlock that kept happening after the retries, or a lock wait timeout (lib/db-errors.ts).
	CONCURRENT_UPDATE: 'CONCURRENT_UPDATE',
	DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
