import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Plugin } from 'vite';

/**
 * HTTP 200 on the SPA's deep links for static hosts.
 *
 * Writes `dist/_redirects` (Netlify, Cloudflare Pages) from one route list,
 * each route with and without a trailing slash, and fails the build if
 * `vercel.json` rewrites a different set, so the hosts cannot drift apart.
 *
 * Only the app's routes are listed — no `/*` catch-all — so real files and
 * unknown URLs keep their own response (the 404 fallback).
 *
 * The rewrite target differs per host, so it is picked at build time:
 * - Cloudflare Pages strips `/index` and `.html` from a `/index.html` target and
 *   rejects the rule as an infinite loop; it needs `/`.
 * - Netlify documents `/index.html` as the SPA target and does not document
 *   `/`; it sets `NETLIFY=true` in its builds, so it gets `/index.html`.
 * Any other build (Cloudflare, local, `wrangler pages dev`) gets `/`.
 */

/** Route patterns in `_redirects`/`vercel.json` syntax. `:id` matches one path segment. */
export default function spaRewrites(routes: string[]): Plugin {
	const sources = routes.flatMap((route) => [route, `${route}/`]);

	return {
		name: 'spa-rewrites',
		apply: 'build',

		async buildStart() {
			// Editors on Windows may save a BOM, which JSON.parse rejects.
			const text = (await readFile(resolve('vercel.json'), 'utf8')).replace(/^﻿/, '');
			const vercel = JSON.parse(text) as {
				rewrites?: { source: string; destination: string }[];
			};
			const actual = (vercel.rewrites ?? []).map((rule) => `${rule.source} -> ${rule.destination}`).sort();
			const expected = sources.map((source) => `${source} -> /index.html`).sort();
			if (actual.join('\n') !== expected.join('\n')) {
				this.error(
					`vercel.json rewrites don't match the SPA routes in vite.config.ts.\nExpected:\n  ${expected.join('\n  ')}\nFound:\n  ${actual.join('\n  ') || '(none)'}`,
				);
			}
		},

		generateBundle() {
			const target = process.env.NETLIFY === 'true' ? '/index.html' : '/';
			const width = Math.max(...sources.map((source) => source.length)) + 2;
			const lines = sources.map((source) => `${source.padEnd(width)}${target}  200`);
			this.emitFile({
				type: 'asset',
				fileName: '_redirects',
				source: [
					'# Generated by vite-plugins/spa-rewrites.ts. Edit the route list in vite.config.ts.',
					`# Rewrite target: ${target} (${target === '/' ? 'Cloudflare Pages and other builds' : 'Netlify build'}).`,
					...lines,
					'',
				].join('\n'),
			});
		},
	};
}
